package window

import (
	"github.com/SpaiR/imgui-go"
	"sdmm/internal/imguiext/style"
)

// ApplyDefaultTheme is shared by the native window and UI rendering tests.
func ApplyDefaultTheme() {
	imgui.StyleColorsDark()

	s := imgui.CurrentStyle()
	s.SetWindowBorderSize(1)
	s.SetChildBorderSize(0)
	s.SetScrollbarSize(10)
	s.SetTabRounding(3)
	s.SetWindowRounding(3)
	s.SetScrollbarRounding(3)
	s.SetPopupRounding(3)
	s.SetFrameRounding(2)

	s.SetColor(imgui.StyleColorText, style.Text)
	s.SetColor(imgui.StyleColorTextDisabled, style.Muted)
	s.SetColor(imgui.StyleColorWindowBg, style.Background)
	s.SetColor(imgui.StyleColorChildBg, imgui.Vec4{})
	s.SetColor(imgui.StyleColorPopupBg, style.Surface)
	s.SetColor(imgui.StyleColorBorder, style.Line)
	s.SetColor(imgui.StyleColorBorderShadow, imgui.Vec4{})
	s.SetColor(imgui.StyleColorFrameBg, style.RGB(0x101923))
	s.SetColor(imgui.StyleColorFrameBgHovered, style.RGB(0x2b3e52))
	s.SetColor(imgui.StyleColorFrameBgActive, style.RGB(0x304b60))
	s.SetColor(imgui.StyleColorTitleBg, style.Background)
	s.SetColor(imgui.StyleColorTitleBgActive, style.Surface)
	s.SetColor(imgui.StyleColorTitleBgCollapsed, style.Background)
	s.SetColor(imgui.StyleColorMenuBarBg, style.Surface)
	s.SetColor(imgui.StyleColorScrollbarBg, style.Background)
	s.SetColor(imgui.StyleColorScrollbarGrab, style.Line)
	s.SetColor(imgui.StyleColorScrollbarGrabHovered, style.Muted)
	s.SetColor(imgui.StyleColorScrollbarGrabActive, style.Teal)
	s.SetColor(imgui.StyleColorCheckMark, style.Teal)
	s.SetColor(imgui.StyleColorSliderGrab, style.Teal)
	s.SetColor(imgui.StyleColorSliderGrabActive, style.RGB(0x83ead9))
	s.SetColor(imgui.StyleColorButton, style.Raised)
	s.SetColor(imgui.StyleColorButtonHovered, style.RGB(0x344a60))
	s.SetColor(imgui.StyleColorButtonActive, style.RGB(0x24524f))
	s.SetColor(imgui.StyleColorHeader, style.RGB(0x294b55))
	s.SetColor(imgui.StyleColorHeaderHovered, style.RGB(0x304557))
	s.SetColor(imgui.StyleColorHeaderActive, style.RGB(0x356a6a))
	s.SetColor(imgui.StyleColorSeparator, style.Line)
	s.SetColor(imgui.StyleColorSeparatorHovered, style.Teal)
	s.SetColor(imgui.StyleColorSeparatorActive, style.Teal)
	s.SetColor(imgui.StyleColorResizeGrip, style.Line)
	s.SetColor(imgui.StyleColorResizeGripHovered, style.Muted)
	s.SetColor(imgui.StyleColorResizeGripActive, style.Teal)
	s.SetColor(imgui.StyleColorTab, style.Surface)
	s.SetColor(imgui.StyleColorTabHovered, style.RGB(0x345968))
	s.SetColor(imgui.StyleColorTabActive, style.RGB(0x294b55))
	s.SetColor(imgui.StyleColorTabUnfocused, style.Background)
	s.SetColor(imgui.StyleColorTabUnfocusedActive, style.Raised)
	s.SetColor(imgui.StyleColorDockingPreview, style.Teal)
	s.SetColor(imgui.StyleColorDockingEmptyBg, style.Background)
	s.SetColor(imgui.StyleColorTableHeaderBg, style.Raised)
	s.SetColor(imgui.StyleColorTableBorderStrong, style.Line)
	s.SetColor(imgui.StyleColorTableBorderLight, style.Surface)
	s.SetColor(imgui.StyleColorTableRowBg, imgui.Vec4{})
	s.SetColor(imgui.StyleColorTableRowBgAlt, imgui.Vec4{X: 1, Y: 1, Z: 1, W: .035})
	s.SetColor(imgui.StyleColorTextSelectedBg, style.RGB(0x386a79))
	s.SetColor(imgui.StyleColorDragDropTarget, style.Amber)
	s.SetColor(imgui.StyleColorNavHighlight, style.Teal)
	s.SetColor(imgui.StyleColorModalWindowDimBg, imgui.Vec4{X: .02, Y: .04, Z: .07, W: .72})
}
